pipeline {
    agent any
 stages {
  stage('Docker image creation') {
           steps {

              sh ' docker pull ubuntu/bind9 '
                  
          }
        }
stage('Docker container run ') {
           steps {

              sh 'docker run -it --name prak ubuntu/bind9 /bin/bash '
                  
          }
        }
                  
     }
  }

