pipeline {
    agent any
 stages {
  stage('Docker Build and Tag') {
           steps {
              
                sh 'docker build -t nginxtest:latest .' 
                  sh 'docker tag nginxtest prasanna2121/nginxtest:latest'
                sh 'docker tag nginxtest prasanna2121/nginxtest:$BUILD_NUMBER'
               
          }
        }
     
  stage('Publish image to Docker Hub') {
          
            steps {
        withDockerRegistry([ credentialsId: "dockerHub", url: "https://hub.docker.com" ]) {
          sh  'docker push prasanna2121/nginxtest:latest'
          sh  'docker push prasanna2121/nginxtest:$BUILD_NUMBER' 
        }
                  
          }
        }
     
      stage('Run Docker container on Jenkins Agent') {
             
            steps {
                sh "docker run -d -p 4030:80 prasanna2121/nginxtest"
 
            
 
            }
        }
    }
}